### ISSUE TITLE
Solid collision issue + Wiggler?

### ISSUE THREAD

**Issue by mackreal** [Gatete/GMEAnniversary#2]
As said in discord

Note to viewer, This is my fangame, It uses this engine and no code has been modified by me to the physics only copy and pasting the repository.
![this happens](https://user-images.githubusercontent.com/39462203/41259299-bd581b0c-6d98-11e8-9b20-b5a891e59992.gif)

CODE:
//Default wall collision

if ((hspeed < 0) && (collision_rectangle(bbox_left-1,bbox_top+4,bbox_left,bbox_bottom-5-abs(hspeed),obj_solid,1,0)))
|| ((hspeed > 0) && (collision_rectangle(bbox_right,bbox_top+4,bbox_right+1,bbox_bottom-5-abs(hspeed),obj_solid,1,0))) {

    //Reverse speed
    hspeed = -hspeed;
    
    //Prevent getting embed on walls
    while (collision_rectangle(bbox_left-1,bbox_top+4,bbox_right,bbox_bottom-5-abs(hspeed),obj_solid,1,0))
        x++;
    while (collision_rectangle(bbox_left,bbox_top+4,bbox_right+1,bbox_bottom-5-abs(hspeed),obj_solid,1,0))
        x--;
}

**Comment by GateteVerde** [comment]
Fixed in v1.3
