### ISSUE TITLE
When imported to Game Maker Studio 2 - Backgrounds have some issues.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Gatete/GMEAnniversary#3]
https://gist.github.com/P3rf3ctXZer0/221bc0ef945bbd2d16b49bd87fe9e08f

**Comment by GateteVerde** [comment]
Can't fix since I do not have Game Maker Studio 2, sorry.

Game Maker Studio 2 turned all backgrounds onto sprites, I dunno why.
