### ISSUE TITLE
two bug about piranha and semisolid

### ISSUE THREAD

**Issue by mariodad3** [Gatete/GMEAnniversary#7]
A bug about  when mario come out a pipe with a piranha in it ，when mario come out pipe ，piranha also come out ，then mario will hurt by the piranha， this bug also exist in the gatete mario engine9.
My suggestion is add or use a parent object replace the playerparent.
A onother bug about when two semisolid is very closed in the y direction，for example ，if semisolid(a) at x = 48 , y = 16,length = 5blocks,semisolid(b) at x = 80 ,y = 32,also length = 5blcoks . if mario walk on semisolid(b) ,and move to rightest , mario will not drop if his head also collision with the semisolid（a）

**Comment by mariodad3** [comment]
I have one more question，if mario go to room b from room a ，then mario return room a . blocks and collectible items if mario hit or collected，it will reset or reappear in the room a .
 It maybe neet add a global variable in those object when it hit or collected by Mario，and clear those variable when level finish or mario dead.
But i dont know add what kind of codes to resolve this problem.

**Comment by GateteVerde** [comment]
For the blocks I recommend using a ds_map variable, check the ace coin object to get an example
